version: '3.5'
services:

  check-yo-self:
    image: check-yo-self:1.0.2
    ports:
      - 5000:80
    environment:
      - CheckYoSelf__employeesApiBaseUrl=http://check-yo-self-api/
      - CheckYoSelf__employeesButtonVisible=true
    depends_on: 
      - check-yo-self-api

  check-yo-self-api:
    image: check-yo-self-api:1.0.4
    ports:
      - 5001:80
    environment:
      - CheckYoSelf__IndexerBaseUri=http://check-yo-self-indexer/
      - Data__DatabaseDriver=MySql
      - Data__MySql__ConnectionString=Server=db;Port=3306;Database=employees;Uid=root;Pwd=checkyoself
      - ASPNETCORE_ENVIRONMENT=Development
    depends_on: 
      - check-yo-self-indexer

  check-yo-self-indexer:
    image: check-yo-self-indexer:1.0.1
    ports:
      - 5002:80
    environment: 
      - Elasticsearch__uri=http://elasticsearch:9200
      - Elasticsearch__username=elastic
      - Elasticsearch__password=ElasticAdmin1
      - Elasticsearch__indexName=employees
      - Elasticsearch__maxBulkInsertCount=100
      - Elasticsearch__numberOfReplicas=1
      - Elasticsearch__numberOfShards=5
      - Elasticsearch__useAuthentication=false
      - ASPNETCORE_ENVIRONMENT=Development

  check-yo-self-bootstrapper:
    image: check-yo-self-bootstrapper:1.0.0
    environment: 
      - APICONTAINER=check-yo-self-api
    depends_on: 
      - check-yo-self-api

networks:
  default:
    external:
      name: platform