apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    run: check-yo-self-api
  name: check-yo-self-api
spec:
  replicas: 1
  strategy: {}
  template:
    metadata:
      labels:
        run: check-yo-self-api
    spec:
      containers:
      - image: check-yo-self-api:1.0.1
        name: check-yo-self-api
        # env:
        # - name: ConfigurationServer__uri
        #   value: http://consul:8500
        ports:
        - containerPort: 80
        resources: {}
      restartPolicy: Always
      # imagePullSecrets:
      # - name: tylerorg
status: {}
---
apiVersion: v1
kind: Service
metadata:
  name: check-yo-self-api
  labels:
    run: check-yo-self-api
spec:
  ports:
  - name: http
    targetPort: 80
    port: 80
  selector:
    run: check-yo-self-api